second  commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -49,7 +49,11 @@ jobs:
           at: /tmp
       - run:
           name: Deploy app
-          command: echo todo && false
+          command: HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
+                    if [ "$HTTPCODE" -ne 200 ];then
+                    echo "heroku app not responding, failing deploy"
+                    exit 1
+                    fi
   back-test-unit:
     <<: *shared-config
     steps:
